# docker-compose.yml (in workspace root)


services:
  citaseps-db:
    container_name: citaseps-sqlserver-db
    image: mcr.microsoft.com/mssql/server:2022-latest # Use the desired SQL Server version
    environment:
      ACCEPT_EULA: "Y" # Required for SQL Server image
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}" # Read password from .env file
      # Optional: Define a default database to be created
      # MSSQL_DB: CitasEPSDb
      # MSSQL_USER: your_app_user # Optional: Create a dedicated user
      # MSSQL_PASSWORD: your_app_user_password # Optional: Password for dedicated user
    ports:
      - "1433:1433" # Map host port 1433 to container port 1433 (default SQL Server)
    volumes:
      - sqlserver_data:/var/opt/mssql # Persist database data
volumes:
  sqlserver_data: # Define the named volume for data persistence
    driver: local 